name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test
    uses: jakepetroules/github-workflows/.github/workflows/swift_package_test.yml@eng/PR-freebsd
    with:
      enable_cross_pr_testing: true
      enable_linux_checks: false
      enable_windows_checks: false
      linux_os_versions: '["amazonlinux2", "bookworm", "noble", "jammy", "rhel-ubi9"]'
      linux_pre_build_command: ./.github/scripts/prebuild.sh
      linux_build_command: 'swift test --no-parallel'
      linux_swift_versions: '["nightly-main", "nightly-6.3"]'
      linux_host_archs: '["x86_64", "aarch64"]'
      freebsd_pre_build_command: ./.github/scripts/prebuild.sh
      freebsd_build_command: 'swift test --no-parallel'
      enable_freebsd_checks: true
      windows_build_timeout: 180
      windows_pre_build_command: 'Invoke-Program .\.github\scripts\prebuild.ps1'
      windows_swift_versions: '["nightly-main", "nightly-6.3"]'
      windows_build_command: 'Invoke-Program swift test --no-parallel'
      enable_linux_static_sdk_build: false
      enable_android_sdk_build: false
      android_sdk_build_command: "swift build --build-tests"
      android_ndk_versions: '["r27d", "r29"]'
      linux_static_sdk_build_command: SWIFTBUILD_STATIC_LINK=1 LLBUILD_STATIC_LINK=1 swift build
      enable_ios_checks: false
      enable_macos_checks: false
      macos_exclude_xcode_versions: "[{\"xcode_version\": \"16.3\"}, {\"xcode_version\": \"16.4\"}]"
      macos_pre_build_command: ./.github/scripts/prebuild.sh
      macos_build_command:
        swift test &&
        /usr/bin/xcrun xcodebuild -workspace . -scheme SwiftBuild-Package -destination generic/platform=iOS
